import { useState } from 'react'
import { Users, BarChart3, Cpu, Bot, ScrollText, Image, Dumbbell, Bell, Settings, Search, Check, X, Activity, DollarSign } from 'lucide-react'
import AdminShell from '../components/AdminShell'
import { adminUsers } from '../data/mock'

const Placeholder = ({title,Icon,text,children}) => <AdminShell title={title}><section className="admin-hero panel"><span className="admin-icon"><Icon size={26}/></span><h2>{title}</h2><p>{text}</p></section>{children}</AdminShell>

export function AdminOverview(){return <AdminShell title="Admin Overview" subtitle="Platform health, users and AI operations."><div className="metric-grid"><AdminMetric label="TOTAL USERS" value="12,482" Icon={Users}/><AdminMetric label="ACTIVE TODAY" value="3,204" Icon={Activity}/><AdminMetric label="AI REQUESTS" value="58,391" Icon={Cpu}/><AdminMetric label="MRR" value="$42.8k" Icon={DollarSign}/></div><div className="dashboard-grid"><section className="panel"><h3>Platform activity</h3><p>Requests over the last 7 days</p><div className="admin-bars">{[52,67,60,81,75,93,86].map((x,i)=><span key={i} style={{height:`${x}%`}}/>)}</div></section><section className="panel"><h3>System status</h3><div className="status-list"><p><i/> API <b>Operational</b></p><p><i/> Database <b>Operational</b></p><p><i/> AI gateway <b>Operational</b></p><p><i className="warn"/> Image moderation <b>Degraded</b></p></div></section></div></AdminShell>}
function AdminMetric({label,value,Icon}){return <article className="metric-card compact"><div><span>{label}</span><h3>{value}</h3></div><i className="purple-icon"><Icon size={22}/></i></article>}

export function AdminUsers(){const [q,setQ]=useState(''); const users=adminUsers.filter(u=>(u.name+u.email).toLowerCase().includes(q.toLowerCase())); return <AdminShell title="Users" subtitle="Search, review and manage user accounts."><div className="toolbar"><div className="searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search users"/></div><button className="btn btn-sm">Export CSV</button></div><section className="panel table-wrap"><table><thead><tr><th>User</th><th>Plan</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.email}><td><strong>{u.name}</strong><small>{u.email}</small></td><td>{u.plan}</td><td><span className={`status ${u.status==='Review'?'review':''}`}>{u.status}</span></td><td><button className="table-btn">View</button></td></tr>)}</tbody></table></section></AdminShell>}

export function AdminAnalytics(){return <Placeholder title="Analytics" Icon={BarChart3} text="Product, retention and engagement analytics are wired to the mock data layer."><div className="macro-grid"><AdminMetric label="7-DAY RETENTION" value="68%" Icon={BarChart3}/><AdminMetric label="AVG SESSION" value="18m" Icon={Activity}/><AdminMetric label="WORKOUTS / USER" value="4.8" Icon={Dumbbell}/><AdminMetric label="CONVERSION" value="7.2%" Icon={Users}/></div></Placeholder>}
export function AIUsage(){return <Placeholder title="AI Usage" Icon={Cpu} text="Track model requests, token usage, latency and estimated cost."><section className="panel usage-list">{[['Coach chat','24,801','42%'],['Workout generator','16,209','28%'],['Nutrition planner','11,904','20%'],['Moderation','5,477','10%']].map(x=><article key={x[0]}><strong>{x[0]}</strong><span>{x[1]} requests</span><b>{x[2]}</b></article>)}</section></Placeholder>}
export function AILogs(){return <Placeholder title="AI Logs" Icon={Bot} text="Review structured AI request and response logs."><LogTable prefix="AI"/></Placeholder>}
export function SystemLogs(){return <Placeholder title="System Logs" Icon={ScrollText} text="Inspect application events, API responses and background jobs."><LogTable prefix="SYS"/></Placeholder>}
function LogTable({prefix}){return <section className="panel table-wrap"><table><thead><tr><th>Time</th><th>Level</th><th>Event</th><th>Latency</th></tr></thead><tbody>{[['01:04:22','INFO',`${prefix}-request-complete`,'412ms'],['01:03:50','INFO',`${prefix}-cache-hit`,'22ms'],['01:02:14','WARN',`${prefix}-retry`,'910ms'],['01:01:09','INFO',`${prefix}-request-complete`,'388ms']].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></section>}

export function Moderation(){const [states,setStates]=useState(['Pending','Pending','Approved']); const set=(i,v)=>setStates(s=>s.map((x,j)=>j===i?v:x)); return <Placeholder title="Image Moderation" Icon={Image} text="Review uploaded progress photos before they become visible."><div className="moderation-grid">{states.map((s,i)=><article className="panel moderation-card" key={i}><div className="moderation-art"><Image size={32}/></div><strong>User #{1042+i}</strong><span className={`status ${s==='Rejected'?'review':''}`}>{s}</span><div><button onClick={()=>set(i,'Approved')}><Check size={16}/> Approve</button><button onClick={()=>set(i,'Rejected')}><X size={16}/> Reject</button></div></article>)}</div></Placeholder>}
export function AdminWorkouts(){return <Placeholder title="Workouts" Icon={Dumbbell} text="Manage workout templates available to the generator and library."><section className="panel table-wrap"><table><thead><tr><th>Template</th><th>Level</th><th>Used</th><th>Status</th></tr></thead><tbody>{[['Upper Strength','Intermediate','4,208','Active'],['Fat Loss HIIT','Advanced','3,914','Active'],['Mobility Reset','Beginner','2,771','Active'],['Runner Build','Intermediate','1,980','Draft']].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></section></Placeholder>}
export function AdminNotifications(){return <Placeholder title="Notifications" Icon={Bell} text="Compose platform announcements and user reminders."><section className="panel form-panel"><label>Title<input placeholder="Announcement title"/></label><label>Message<textarea rows="5" placeholder="Write a notification..."/></label><div className="form-two"><label>Audience<select><option>All users</option><option>Pro users</option><option>Inactive users</option></select></label><label>Delivery<select><option>In-app</option><option>Email + in-app</option></select></label></div><button className="btn">Send notification</button></section></Placeholder>}
export function AdminSettings(){const [saved,setSaved]=useState(false); return <AdminShell title="Platform Settings" subtitle="Feature flags, limits and AI configuration."><section className="admin-hero panel settings-card"><span className="admin-icon"><Settings size={26}/></span><h2>Platform Settings</h2><p>This module is wired to the mock API layer and ready for its data view.</p></section><section className="panel settings-form"><h3>Configuration</h3><div className="form-two"><label>Default AI model<select><option>GPT-compatible model</option><option>Local model</option></select></label><label>Daily request limit<input defaultValue="100"/></label><label>Image moderation<select><option>Enabled</option><option>Disabled</option></select></label><label>Maintenance mode<select><option>Off</option><option>On</option></select></label></div><button className="btn" onClick={()=>setSaved(true)}>{saved?'Saved ✓':'Save settings'}</button></section></AdminShell>}
