import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Brand from '../components/Brand'

export function Login(){
  const [role,setRole]=useState('user'); const [email,setEmail]=useState('ayaan@fitcoach.ai'); const [password,setPassword]=useState('password'); const navigate=useNavigate()
  const submit=e=>{e.preventDefault(); localStorage.setItem('fitcoach-role',role); navigate(role==='admin'?'/admin':'/dashboard')}
  return <div className="auth-page"><div className="auth-wrap"><Brand/><form className="auth-card" onSubmit={submit}><h1>Welcome back</h1><p>Sign in to continue your training journey.</p><div className="role-tabs"><button type="button" onClick={()=>setRole('user')} className={role==='user'?'active':''}>User</button><button type="button" onClick={()=>setRole('admin')} className={role==='admin'?'active':''}>Admin</button></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><Link to="#" className="forgot">Forgot password?</Link><button className="btn auth-btn">Sign in</button><small>JWT-ready: the token is stored via the API layer on success.</small></form><p className="auth-bottom">New here? <Link to="/register">Create an account</Link></p></div></div>
}

export function Register(){
 const navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:'',confirm:'',age:'',gender:'Male',height:'',weight:'',goal:'Fat Loss'})
 const change=e=>setForm({...form,[e.target.name]:e.target.value}); const submit=e=>{e.preventDefault(); localStorage.setItem('fitcoach-profile',JSON.stringify(form)); navigate('/dashboard')}
 return <div className="auth-page"><div className="auth-wrap register-wrap"><Brand/><form className="auth-card register-card" onSubmit={submit}><h1>Create your account</h1><p>Tell us about you so the AI can build the right plan.</p><label>Full name<input name="name" value={form.name} onChange={change} required/></label><label>Email<input name="email" type="email" value={form.email} onChange={change} required/></label><div className="form-two"><label>Password<input name="password" type="password" value={form.password} onChange={change} required/></label><label>Confirm password<input name="confirm" type="password" value={form.confirm} onChange={change} required/></label><label>Age<input name="age" type="number" value={form.age} onChange={change}/></label><label>Gender<select name="gender" value={form.gender} onChange={change}><option>Male</option><option>Female</option><option>Other</option></select></label><label>Height (cm)<input name="height" type="number" value={form.height} onChange={change}/></label><label>Weight (kg)<input name="weight" type="number" value={form.weight} onChange={change}/></label></div><label>Fitness goal<select name="goal" value={form.goal} onChange={change}><option>Fat Loss</option><option>Build Muscle</option><option>Maintain Weight</option><option>Improve Endurance</option></select></label><button className="btn auth-btn">Create account</button></form><p className="auth-bottom">Already registered? <Link to="/login">Sign in</Link></p></div></div>
}
