import { Scale, Flame, Footprints, Trophy, Activity, Droplets } from 'lucide-react'
import UserShell from '../components/UserShell'
import { weekly, weightTrend } from '../data/mock'

function Metric({title,value,unit,delta,note,Icon,bad}){return <article className="metric-card"><div><span>{title}</span><h3>{value} <small>{unit}</small></h3><p className={bad?'bad':'good'}>{bad?'↘':'↗'} {delta} <em>{note}</em></p></div><i><Icon size={24}/></i></article>}
function Bars(){const max=Math.max(...weekly); return <div className="bar-chart">{weekly.map((v,i)=><div className="bar-col" key={i}><span style={{height:`${(v/max)*82}%`}}></span><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>)}</div>}
function LineChart(){const min=Math.min(...weightTrend)-.5,max=Math.max(...weightTrend)+.5; const pts=weightTrend.map((v,i)=>`${i*20},${100-((v-min)/(max-min))*70}`).join(' '); return <div className="line-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#27db9a" stopOpacity=".35"/><stop offset="1" stopColor="#27db9a" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${pts} 100,100`} fill="url(#fill)"/><polyline points={pts} fill="none" stroke="#27db9a" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/></svg><div className="week-labels">{weightTrend.map((_,i)=><span key={i}>W{i+1}</span>)}</div></div>}

export default function Dashboard(){return <UserShell title="Welcome back, Ayaan" subtitle="Here is how your week is shaping up."><div className="metric-grid"><Metric title="CURRENT WEIGHT" value="79.4" unit="kg" delta="2.1%" note="vs last month" Icon={Scale} bad/><Metric title="CALORIES BURNED" value="3,930" unit="kcal" delta="8.4%" note="this week" Icon={Flame}/><Metric title="STEPS TODAY" value="9,412" unit="" delta="4.2%" note="goal 10,000" Icon={Footprints}/><Metric title="STREAK" value="18" unit="days" delta="12%" note="personal best 24" Icon={Trophy}/></div><div className="dashboard-grid"><section className="panel weekly-panel"><h3>Weekly activity</h3><p>Calories burned per session</p><Bars/></section><section className="panel targets"><h3>Today's targets</h3><Target Icon={Activity} label="Workout completion" value="78%" width="78"/><Target Icon={Droplets} label="Water intake (2.1 / 3 L)" value="70%" width="70"/><Target Icon={Flame} label="Calorie goal (1,840 / 2,400)" value="61%" width="61"/><div className="bmi"><span>BMI</span><strong>23.1</strong><small>Healthy range</small></div></section></div><section className="panel trend"><h3>Weight trend</h3><p>Last 6 weeks</p><LineChart/></section></UserShell>}
function Target({Icon,label,value,width}){return <div className="target"><div><span><Icon size={15}/>{label}</span><b>{value}</b></div><i><em style={{width:`${width}%`}}/></i></div>}
