import { useMemo, useState } from 'react'
import { Bot, Send, Dumbbell, Apple, Activity, Camera, Bell, User, Sparkles, Clock, Flame, Upload, CheckCircle2, Search } from 'lucide-react'
import UserShell from '../components/UserShell'
import { workoutLibrary, notifications, weightTrend } from '../data/mock'

export function Coach(){
  const [messages,setMessages]=useState([{from:'ai',text:'Hi Ayaan. I’m your AI fitness coach. Ask me about training, recovery, nutrition or your weekly plan.'}]); const [text,setText]=useState('')
  const send=e=>{e.preventDefault(); if(!text.trim())return; const q=text.trim(); setMessages(m=>[...m,{from:'user',text:q},{from:'ai',text:'Based on your current goal and recent activity, keep today moderate: 35–45 minutes of strength work, finish with 10 minutes of easy cardio, and prioritize protein plus hydration after training.'}]); setText('')}
  return <UserShell title="AI Coach" subtitle="Personal guidance powered by your fitness context."><div className="module-grid coach-grid"><section className="panel chat-panel"><div className="module-title"><span className="feature-icon"><Bot size={20}/></span><div><h3>AI Coach</h3><p>RAG-ready mock conversation</p></div></div><div className="chat-stream">{messages.map((m,i)=><div key={i} className={`bubble ${m.from}`}>{m.text}</div>)}</div><form className="chat-input" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about workouts, recovery, calories..."/><button className="btn btn-icon"><Send size={17}/></button></form></section><aside className="panel quick-panel"><h3>Quick prompts</h3>{['Build my workout for today','How much protein should I eat?','Should I train with sore legs?','Review my weekly progress'].map(x=><button key={x} onClick={()=>setText(x)}>{x}</button>)}</aside></div></UserShell>
}

export function WorkoutGenerator(){
  const [generated,setGenerated]=useState(false)
  return <UserShell title="AI Workout Generator" subtitle="Create a personalized plan in seconds."><div className="module-grid"><section className="panel form-panel"><h3>Workout preferences</h3><div className="form-two"><label>Goal<select><option>Fat Loss</option><option>Build Muscle</option><option>Strength</option></select></label><label>Experience<select><option>Intermediate</option><option>Beginner</option><option>Advanced</option></select></label><label>Days / week<select><option>4 days</option><option>3 days</option><option>5 days</option></select></label><label>Session length<select><option>45 minutes</option><option>30 minutes</option><option>60 minutes</option></select></label></div><label>Equipment<select><option>Full gym</option><option>Dumbbells only</option><option>Bodyweight</option></select></label><button className="btn wide" onClick={()=>setGenerated(true)}><Sparkles size={17}/> Generate workout plan</button></section><section className="panel result-panel"><h3>{generated?'Your generated plan':'Plan preview'}</h3>{generated?<div className="plan-days">{['Mon · Upper Body','Tue · Lower Body','Thu · Push + Core','Sat · Pull + Conditioning'].map((d,i)=><article key={d}><div><strong>{d}</strong><small>{['Bench press · Rows · Shoulder press','Squats · RDL · Lunges','Incline press · Dips · Planks','Pull-ups · Curls · 12 min intervals'][i]}</small></div><span>45 min</span></article>)}</div>:<div className="empty-state"><Dumbbell size={42}/><p>Choose your preferences and generate a plan.</p></div>}</section></div></UserShell>
}

export function Nutrition(){return <UserShell title="AI Nutrition Plan" subtitle="Macro-aware meals matched to your goal."><div className="macro-grid"><Macro label="Calories" value="2,400" unit="kcal"/><Macro label="Protein" value="168" unit="g"/><Macro label="Carbs" value="245" unit="g"/><Macro label="Fats" value="72" unit="g"/></div><section className="panel"><div className="section-head"><div><h3>Today’s meal plan</h3><p>Balanced for fat loss with high protein.</p></div><button className="btn btn-sm"><Sparkles size={15}/> Regenerate</button></div><div className="meal-list">{[['Breakfast','Greek yogurt bowl + oats + berries','520 kcal'],['Lunch','Grilled chicken rice bowl + vegetables','690 kcal'],['Snack','Protein shake + banana','330 kcal'],['Dinner','Salmon, potatoes + green salad','760 kcal']].map(([a,b,c])=><article key={a}><span className="feature-icon"><Apple size={18}/></span><div><strong>{a}</strong><p>{b}</p></div><b>{c}</b></article>)}</div></section></UserShell>}
function Macro({label,value,unit}){return <article className="metric-card compact"><div><span>{label.toUpperCase()}</span><h3>{value} <small>{unit}</small></h3></div><i><Apple size={22}/></i></article>}

export function Library(){const [q,setQ]=useState(''); const list=useMemo(()=>workoutLibrary.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())),[q]); return <UserShell title="Workout Library" subtitle="Browse reusable workouts and training sessions."><div className="toolbar"><div className="searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search workouts"/></div><button className="btn btn-sm">All workouts</button></div><div className="cards-grid">{list.map(w=><article className="workout-card" key={w.title}><div className="workout-art"><Dumbbell size={34}/></div><h3>{w.title}</h3><p>{w.level}</p><div><span><Clock size={15}/>{w.time}</span><span><Flame size={15}/>{w.kcal} kcal</span></div><button className="btn btn-ghost wide">View workout</button></article>)}</div></UserShell>}

export function Progress(){const pts=weightTrend.map((v,i)=>`${i*20},${90-(v-78)*18}`).join(' '); return <UserShell title="Progress Tracking" subtitle="See the trends behind your consistency."><div className="macro-grid"><Macro label="Weight change" value="-3.1" unit="kg"/><Macro label="Body fat" value="18.2" unit="%"/><Macro label="Workouts" value="22" unit="sessions"/><Macro label="Avg. sleep" value="7.4" unit="hrs"/></div><section className="panel"><h3>6-week body weight</h3><p>Steady downward trend</p><div className="progress-big-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="#27db9a" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg></div></section></UserShell>}

export function Photos(){const [files,setFiles]=useState([]); const add=e=>setFiles([...e.target.files].map(f=>({name:f.name,url:URL.createObjectURL(f)}))); return <UserShell title="Progress Photos" subtitle="Track visual changes over time."><section className="panel upload-panel"><label className="dropzone"><Upload size={32}/><strong>Upload progress photos</strong><span>PNG or JPG · files stay local in this demo</span><input type="file" accept="image/*" multiple onChange={add}/></label></section><div className="photo-grid">{files.length?files.map(f=><article key={f.name}><img src={f.url}/><span><CheckCircle2 size={15}/> Ready for moderation</span></article>):['Week 1','Week 3','Week 6'].map(x=><article className="photo-placeholder" key={x}><Camera size={30}/><strong>{x}</strong><span>Demo photo slot</span></article>)}</div></UserShell>}

export function Notifications(){return <UserShell title="Notifications" subtitle="Your reminders and AI updates."><section className="panel notification-list">{notifications.map((n,i)=><article key={i}><span className="feature-icon"><Bell size={18}/></span><div><strong>{n.title}</strong><p>{n.text}</p></div><small>{n.time}</small></article>)}</section></UserShell>}

export function Profile(){const [saved,setSaved]=useState(false); return <UserShell title="Profile & Settings" subtitle="Manage personal details and training preferences."><div className="module-grid"><section className="panel form-panel"><div className="module-title"><span className="feature-icon"><User size={20}/></span><div><h3>Ayaan Khan</h3><p>Pro member · joined 2026</p></div></div><div className="form-two"><label>Full name<input defaultValue="Ayaan Khan"/></label><label>Email<input defaultValue="ayaan@fitcoach.ai"/></label><label>Height (cm)<input defaultValue="185"/></label><label>Weight (kg)<input defaultValue="79.4"/></label><label>Goal<select defaultValue="Fat Loss"><option>Fat Loss</option><option>Build Muscle</option></select></label><label>Training days<select defaultValue="4"><option value="4">4 days/week</option><option value="5">5 days/week</option></select></label></div><button className="btn" onClick={()=>setSaved(true)}>{saved?'Saved ✓':'Save changes'}</button></section><aside className="panel quick-panel"><h3>Account</h3><button>Change password</button><button>Export my data</button><button>Notification preferences</button><button className="danger-text">Delete account</button></aside></div></UserShell>}
